name: Pushing Updated Image CI
on:
  push:
    branches:
      - main
    paths:
      - metadata/Dockerfile  
      
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Logging into GitHub Container Registry  
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: j-stat
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Check Dockerfile and Update Image 
        run: |
          cd metadata
          if [ cat Dockerfile | grep . | wc -l  -gt 1 ]; then
            dockername=$(cat Dockerfile | grep . | cut -d'/' -f3 | cut -d':' -f1)
            new_tag=$(echo $(TZ=EST5EDT date +%b_%d_%I-%M-%S_%Y) | tr '[:upper:]' '[:lower:]')
            echo $dockername
            echo $new_tag
            sudo snap install yq
            echo "Updating image from Dockerfile"
            docker build . -t $dockername
            docker tag $dockername ghcr.io/compbiocore/$dockername:$new_tag
            docker push ghcr.io/compbiocore/$dockername:$new_tag
          fi
